<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kecamatan1 = [
            ['id_kota' => 1, 'nama_kecamatan' => "NANGGUNG"],
			['id_kota' => 1, 'nama_kecamatan' => "LEUWILIANG"],
			['id_kota' => 1, 'nama_kecamatan' => "LEUWISADENG"],
			['id_kota' => 1, 'nama_kecamatan' => "PAMIJAHAN"],
			['id_kota' => 1, 'nama_kecamatan' => "CIBUNGBULANG"],
			['id_kota' => 1, 'nama_kecamatan' => "CIAMPEA"],
			['id_kota' => 1, 'nama_kecamatan' => "TENJOLAYA"],
			['id_kota' => 1, 'nama_kecamatan' => "DRAMAGA"],
			['id_kota' => 1, 'nama_kecamatan' => "CIOMAS"],
			['id_kota' => 1, 'nama_kecamatan' => "TAMANSARI"],
			['id_kota' => 1, 'nama_kecamatan' => "CIJERUK"],
			['id_kota' => 1, 'nama_kecamatan' => "CIGOMBONG"],
			['id_kota' => 1, 'nama_kecamatan' => "CARINGIN"],
			['id_kota' => 1, 'nama_kecamatan' => "CIAWI"],
			['id_kota' => 1, 'nama_kecamatan' => "CISARUA"],
			['id_kota' => 1, 'nama_kecamatan' => "MEGAMENDUNG"],
			['id_kota' => 1, 'nama_kecamatan' => "SUKARAJA"],
			['id_kota' => 1, 'nama_kecamatan' => "BABAKAN MADANG"],
			['id_kota' => 1, 'nama_kecamatan' => "SUKAMAKMUR"],
			['id_kota' => 1, 'nama_kecamatan' => "CARIU"],
			['id_kota' => 1, 'nama_kecamatan' => "TANJUNGSARI"],
			['id_kota' => 1, 'nama_kecamatan' => "JONGGOL"],
			['id_kota' => 1, 'nama_kecamatan' => "CILEUNGSI"],
			['id_kota' => 1, 'nama_kecamatan' => "KELAPA NUNGGAL"],
			['id_kota' => 1, 'nama_kecamatan' => "GUNUNG PUTRI"],
			['id_kota' => 1, 'nama_kecamatan' => "CITEUREUP"],
			['id_kota' => 1, 'nama_kecamatan' => "CIBINONG"],
			['id_kota' => 1, 'nama_kecamatan' => "BOJONG GEDE"],
			['id_kota' => 1, 'nama_kecamatan' => "TAJUR HALANG"],
			['id_kota' => 1, 'nama_kecamatan' => "KEMANG"],
			['id_kota' => 1, 'nama_kecamatan' => "RANCA BUNGUR"],
			['id_kota' => 1, 'nama_kecamatan' => "PARUNG"],
			['id_kota' => 1, 'nama_kecamatan' => "CISEENG"],
			['id_kota' => 1, 'nama_kecamatan' => "GUNUNG SINDUR"],
			['id_kota' => 1, 'nama_kecamatan' => "RUMPIN"],
			['id_kota' => 1, 'nama_kecamatan' => "CIGUDEG"],
			['id_kota' => 1, 'nama_kecamatan' => "SUKAJAYA"],
			['id_kota' => 1, 'nama_kecamatan' => "JASINGA"],
			['id_kota' => 1, 'nama_kecamatan' => "TENJO"],
			//1000
			['id_kota' => 1, 'nama_kecamatan' => "PARUNG PANJANG"],
			['id_kota' => 2, 'nama_kecamatan' => "CIEMAS"],
			['id_kota' => 2, 'nama_kecamatan' => "CIRACAP"],
			['id_kota' => 2, 'nama_kecamatan' => "WALURAN"],
			['id_kota' => 2, 'nama_kecamatan' => "SURADE"],
			['id_kota' => 2, 'nama_kecamatan' => "CIBITUNG"],
			['id_kota' => 2, 'nama_kecamatan' => "JAMPANG KULON"],
			['id_kota' => 2, 'nama_kecamatan' => "CIMANGGU"],
			['id_kota' => 2, 'nama_kecamatan' => "KALI BUNDER"],
			['id_kota' => 2, 'nama_kecamatan' => "TEGAL BULEUD"],
			['id_kota' => 2, 'nama_kecamatan' => "CIDOLOG"],
			['id_kota' => 2, 'nama_kecamatan' => "SAGARANTEN"],
			['id_kota' => 2, 'nama_kecamatan' => "CIDADAP"],
			['id_kota' => 2, 'nama_kecamatan' => "CURUGKEMBAR"],
			['id_kota' => 2, 'nama_kecamatan' => "PABUARAN"],
			['id_kota' => 2, 'nama_kecamatan' => "LENGKONG"],
			['id_kota' => 2, 'nama_kecamatan' => "PALABUHANRATU"],
			['id_kota' => 2, 'nama_kecamatan' => "SIMPENAN"],
			['id_kota' => 2, 'nama_kecamatan' => "WARUNG KIARA"],
			['id_kota' => 2, 'nama_kecamatan' => "BANTARGADUNG"],
			['id_kota' => 2, 'nama_kecamatan' => "JAMPANG TENGAH"],
			['id_kota' => 2, 'nama_kecamatan' => "PURABAYA"],
			['id_kota' => 2, 'nama_kecamatan' => "CIKEMBAR"],
			['id_kota' => 2, 'nama_kecamatan' => "NYALINDUNG"],
			['id_kota' => 2, 'nama_kecamatan' => "GEGER BITUNG"],
			['id_kota' => 2, 'nama_kecamatan' => "SUKARAJA"],
			['id_kota' => 2, 'nama_kecamatan' => "KEBONPEDES"],
			['id_kota' => 2, 'nama_kecamatan' => "CIREUNGHAS"],
			['id_kota' => 2, 'nama_kecamatan' => "SUKALARANG"],
			['id_kota' => 2, 'nama_kecamatan' => "SUKABUMI"],
			['id_kota' => 2, 'nama_kecamatan' => "KADUDAMPIT"],
			['id_kota' => 2, 'nama_kecamatan' => "CISAAT"],
			['id_kota' => 2, 'nama_kecamatan' => "GUNUNGGURUH"],
			['id_kota' => 2, 'nama_kecamatan' => "CIBADAK"],
			['id_kota' => 2, 'nama_kecamatan' => "CICANTAYAN"],
			['id_kota' => 2, 'nama_kecamatan' => "CARINGIN"],
			['id_kota' => 2, 'nama_kecamatan' => "NAGRAK"],
			['id_kota' => 2, 'nama_kecamatan' => "CIAMBAR"],
			['id_kota' => 2, 'nama_kecamatan' => "CICURUG"],
			['id_kota' => 2, 'nama_kecamatan' => "CIDAHU"],
			['id_kota' => 2, 'nama_kecamatan' => "PARAKAN SALAK"],
			['id_kota' => 2, 'nama_kecamatan' => "PARUNG KUDA"],
			['id_kota' => 2, 'nama_kecamatan' => "BOJONG GENTENG"],
			['id_kota' => 2, 'nama_kecamatan' => "KALAPA NUNGGAL"],
			['id_kota' => 2, 'nama_kecamatan' => "CIKIDANG"],
			['id_kota' => 2, 'nama_kecamatan' => "CISOLOK"],
			['id_kota' => 2, 'nama_kecamatan' => "CIKAKAK"],
			['id_kota' => 2, 'nama_kecamatan' => "KABANDUNGAN"],
			['id_kota' => 3, 'nama_kecamatan' => "AGRABINTA"],
			['id_kota' => 3, 'nama_kecamatan' => "LELES"],
			['id_kota' => 3, 'nama_kecamatan' => "SINDANGBARANG"],
			['id_kota' => 3, 'nama_kecamatan' => "CIDAUN"],
			['id_kota' => 3, 'nama_kecamatan' => "NARINGGUL"],
			['id_kota' => 3, 'nama_kecamatan' => "CIBINONG"],
			['id_kota' => 3, 'nama_kecamatan' => "CIKADU"],
			['id_kota' => 3, 'nama_kecamatan' => "TANGGEUNG"],
			['id_kota' => 3, 'nama_kecamatan' => "PASIRKUDA"],
			['id_kota' => 3, 'nama_kecamatan' => "KADUPANDAK"],
			['id_kota' => 3, 'nama_kecamatan' => "CIJATI"],
			['id_kota' => 3, 'nama_kecamatan' => "TAKOKAK"],
			['id_kota' => 3, 'nama_kecamatan' => "SUKANAGARA"],
			['id_kota' => 3, 'nama_kecamatan' => "PAGELARAN"],
			['id_kota' => 3, 'nama_kecamatan' => "CAMPAKA"],
			['id_kota' => 3, 'nama_kecamatan' => "CAMPAKA MULYA"],
			['id_kota' => 3, 'nama_kecamatan' => "CIBEBER"],
			['id_kota' => 3, 'nama_kecamatan' => "WARUNGKONDANG"],
			['id_kota' => 3, 'nama_kecamatan' => "GEKBRONG"],
			['id_kota' => 3, 'nama_kecamatan' => "CILAKU"],
			['id_kota' => 3, 'nama_kecamatan' => "SUKALUYU"],
			['id_kota' => 3, 'nama_kecamatan' => "BOJONGPICUNG"],
			['id_kota' => 3, 'nama_kecamatan' => "HAURWANGI"],
			['id_kota' => 3, 'nama_kecamatan' => "CIRANJANG"],
			['id_kota' => 3, 'nama_kecamatan' => "MANDE"],
			['id_kota' => 3, 'nama_kecamatan' => "KARANGTENGAH"],
			['id_kota' => 3, 'nama_kecamatan' => "CIANJUR"],
			['id_kota' => 3, 'nama_kecamatan' => "CUGENANG"],
			['id_kota' => 3, 'nama_kecamatan' => "PACET"],
			['id_kota' => 3, 'nama_kecamatan' => "CIPANAS"],
			['id_kota' => 3, 'nama_kecamatan' => "SUKARESMI"],
			['id_kota' => 3, 'nama_kecamatan' => "CIKALONGKULON"],
			['id_kota' => 4, 'nama_kecamatan' => "CIWIDEY"],
			['id_kota' => 4, 'nama_kecamatan' => "RANCABALI"],
			['id_kota' => 4, 'nama_kecamatan' => "PASIRJAMBU"],
			['id_kota' => 4, 'nama_kecamatan' => "CIMAUNG"],
			['id_kota' => 4, 'nama_kecamatan' => "PANGALENGAN"],
			['id_kota' => 4, 'nama_kecamatan' => "KERTASARI"],
			['id_kota' => 4, 'nama_kecamatan' => "PACET"],
			['id_kota' => 4, 'nama_kecamatan' => "IBUN"],
			['id_kota' => 4, 'nama_kecamatan' => "PASEH"],
			['id_kota' => 4, 'nama_kecamatan' => "CIKANCUNG"],
			['id_kota' => 4, 'nama_kecamatan' => "CICALENGKA"],
			['id_kota' => 4, 'nama_kecamatan' => "NAGREG"],
			['id_kota' => 4, 'nama_kecamatan' => "RANCAEKEK"],
			['id_kota' => 4, 'nama_kecamatan' => "MAJALAYA"],
			['id_kota' => 4, 'nama_kecamatan' => "SOLOKAN JERUK"],
			['id_kota' => 4, 'nama_kecamatan' => "CIPARAY"],
			['id_kota' => 4, 'nama_kecamatan' => "BALEENDAH"],
			['id_kota' => 4, 'nama_kecamatan' => "ARJASARI"],
			['id_kota' => 4, 'nama_kecamatan' => "BANJARAN"],
			['id_kota' => 4, 'nama_kecamatan' => "CANGKUANG"],
			['id_kota' => 4, 'nama_kecamatan' => "PAMEUNGPEUK"],
			['id_kota' => 4, 'nama_kecamatan' => "KATAPANG"],
			['id_kota' => 4, 'nama_kecamatan' => "SOREANG"],
			['id_kota' => 4, 'nama_kecamatan' => "KUTAWARINGIN"],
			['id_kota' => 4, 'nama_kecamatan' => "MARGAASIH"],
			['id_kota' => 4, 'nama_kecamatan' => "MARGAHAYU"],
			['id_kota' => 4, 'nama_kecamatan' => "DAYEUHKOLOT"],
			['id_kota' => 4, 'nama_kecamatan' => "BOJONGSOANG"],
			['id_kota' => 4, 'nama_kecamatan' => "CILEUNYI"],
			['id_kota' => 4, 'nama_kecamatan' => "CILENGKRANG"],
			['id_kota' => 4, 'nama_kecamatan' => "CIMENYAN"],
			['id_kota' => 5, 'nama_kecamatan' => "CISEWU"],
			['id_kota' => 5, 'nama_kecamatan' => "CARINGIN"],
			['id_kota' => 5, 'nama_kecamatan' => "TALEGONG"],
			['id_kota' => 5, 'nama_kecamatan' => "BUNGBULANG"],
			['id_kota' => 5, 'nama_kecamatan' => "MEKARMUKTI"],
			['id_kota' => 5, 'nama_kecamatan' => "PAMULIHAN"],
			['id_kota' => 5, 'nama_kecamatan' => "PAKENJENG"],
			['id_kota' => 5, 'nama_kecamatan' => "CIKELET"],
			['id_kota' => 5, 'nama_kecamatan' => "PAMEUNGPEUK"],
			['id_kota' => 5, 'nama_kecamatan' => "CIBALONG"],
			['id_kota' => 5, 'nama_kecamatan' => "CISOMPET"],
			['id_kota' => 5, 'nama_kecamatan' => "PEUNDEUY"],
			['id_kota' => 5, 'nama_kecamatan' => "SINGAJAYA"],
			['id_kota' => 5, 'nama_kecamatan' => "CIHURIP"],
            ['id_kota' => 5, 'nama_kecamatan' => "CIKAJANG"],
            ['id_kota' => 5, 'nama_kecamatan' => "BANJARWANGI"],
			['id_kota' => 5, 'nama_kecamatan' => "CILAWU"],
			['id_kota' => 5, 'nama_kecamatan' => "BAYONGBONG"],
			['id_kota' => 5, 'nama_kecamatan' => "CIGEDUG"],
			['id_kota' => 5, 'nama_kecamatan' => "CISURUPAN"],
			['id_kota' => 5, 'nama_kecamatan' => "SUKARESMI"],
			['id_kota' => 5, 'nama_kecamatan' => "SAMARANG"],
			['id_kota' => 5, 'nama_kecamatan' => "PASIRWANGI"],
			['id_kota' => 5, 'nama_kecamatan' => "TAROGONG KIDUL"],
			['id_kota' => 5, 'nama_kecamatan' => "TAROGONG KALER"],
			['id_kota' => 5, 'nama_kecamatan' => "GARUT KOTA"],
			['id_kota' => 5, 'nama_kecamatan' => "KARANGPAWITAN"],
			['id_kota' => 5, 'nama_kecamatan' => "WANARAJA"],
			['id_kota' => 5, 'nama_kecamatan' => "SUCINARAJA"],
			['id_kota' => 5, 'nama_kecamatan' => "PANGATIKAN"],
			['id_kota' => 5, 'nama_kecamatan' => "SUKAWENING"],
			['id_kota' => 5, 'nama_kecamatan' => "KARANGTENGAH"],
			['id_kota' => 5, 'nama_kecamatan' => "BANYURESMI"],
			['id_kota' => 5, 'nama_kecamatan' => "LELES"],
			['id_kota' => 5, 'nama_kecamatan' => "LEUWIGOONG"],
			['id_kota' => 5, 'nama_kecamatan' => "CIBATU"],
			['id_kota' => 5, 'nama_kecamatan' => "KERSAMANAH"],
			['id_kota' => 5, 'nama_kecamatan' => "CIBIUK"],
			['id_kota' => 5, 'nama_kecamatan' => "KADUNGORA"],
			['id_kota' => 5, 'nama_kecamatan' => "BLUBUR LIMBANGAN"],
			['id_kota' => 5, 'nama_kecamatan' => "SELAAWI"],
			['id_kota' => 5, 'nama_kecamatan' => "MALANGBONG"],
			['id_kota' => 6, 'nama_kecamatan' => "CIPATUJAH"],
			['id_kota' => 6, 'nama_kecamatan' => "KARANGNUNGGAL"],
			['id_kota' => 6, 'nama_kecamatan' => "CIKALONG"],
			['id_kota' => 6, 'nama_kecamatan' => "PANCATENGAH"],
			['id_kota' => 6, 'nama_kecamatan' => "CIKATOMAS"],
			['id_kota' => 6, 'nama_kecamatan' => "CIBALONG"],
			['id_kota' => 6, 'nama_kecamatan' => "PARUNGPONTENG"],
			['id_kota' => 6, 'nama_kecamatan' => "BANTARKALONG"],
			['id_kota' => 6, 'nama_kecamatan' => "BOJONGASIH"],
			['id_kota' => 6, 'nama_kecamatan' => "CULAMEGA"],
			['id_kota' => 6, 'nama_kecamatan' => "BOJONGGAMBIR"],
			['id_kota' => 6, 'nama_kecamatan' => "SODONGHILIR"],
			['id_kota' => 6, 'nama_kecamatan' => "TARAJU"],
			['id_kota' => 6, 'nama_kecamatan' => "SALAWU"],
			['id_kota' => 6, 'nama_kecamatan' => "PUSPAHIANG"],
			['id_kota' => 6, 'nama_kecamatan' => "TANJUNGJAYA"],
			['id_kota' => 6, 'nama_kecamatan' => "SUKARAJA"],
			['id_kota' => 6, 'nama_kecamatan' => "SALOPA"],
			['id_kota' => 6, 'nama_kecamatan' => "JATIWARAS"],
			['id_kota' => 6, 'nama_kecamatan' => "CINEAM"],
			['id_kota' => 6, 'nama_kecamatan' => "KARANGJAYA"],
			['id_kota' => 6, 'nama_kecamatan' => "MANONJAYA"],
			['id_kota' => 6, 'nama_kecamatan' => "GUNUNGTANJUNG"],
			['id_kota' => 6, 'nama_kecamatan' => "SINGAPARNA"],
			['id_kota' => 6, 'nama_kecamatan' => "SUKARAME"],
			['id_kota' => 6, 'nama_kecamatan' => "MANGUNREJA"],
			['id_kota' => 6, 'nama_kecamatan' => "CIGALONTANG"],
			['id_kota' => 6, 'nama_kecamatan' => "LEUWISARI"],
			['id_kota' => 6, 'nama_kecamatan' => "SARIWANGI"],
			['id_kota' => 6, 'nama_kecamatan' => "PADAKEMBANG"],
			['id_kota' => 6, 'nama_kecamatan' => "SUKARATU"],
			['id_kota' => 6, 'nama_kecamatan' => "CISAYONG"],
			['id_kota' => 6, 'nama_kecamatan' => "SUKAHENING"],
			['id_kota' => 6, 'nama_kecamatan' => "RAJAPOLAH"],
			['id_kota' => 6, 'nama_kecamatan' => "JAMANIS"],
			['id_kota' => 6, 'nama_kecamatan' => "CIAWI"],
			['id_kota' => 6, 'nama_kecamatan' => "KADIPATEN"],
			['id_kota' => 6, 'nama_kecamatan' => "PAGERAGEUNG"],
			['id_kota' => 6, 'nama_kecamatan' => "SUKARESIK"],
			['id_kota' => 7, 'nama_kecamatan' => "BANJARSARI"],
			['id_kota' => 7, 'nama_kecamatan' => "LAKBOK"],
			['id_kota' => 7, 'nama_kecamatan' => "PURWADADI"],
			['id_kota' => 7, 'nama_kecamatan' => "PAMARICAN"],
			['id_kota' => 7, 'nama_kecamatan' => "CIDOLOG"],
			['id_kota' => 7, 'nama_kecamatan' => "CIMARAGAS"],
			['id_kota' => 7, 'nama_kecamatan' => "CIJEUNGJING"],
			['id_kota' => 7, 'nama_kecamatan' => "CISAGA"],
			['id_kota' => 7, 'nama_kecamatan' => "TAMBAKSARI"],
			['id_kota' => 7, 'nama_kecamatan' => "RANCAH"],
			['id_kota' => 7, 'nama_kecamatan' => "RAJADESA"],
			['id_kota' => 7, 'nama_kecamatan' => "SUKADANA"],
			['id_kota' => 7, 'nama_kecamatan' => "CIAMIS"],
			['id_kota' => 7, 'nama_kecamatan' => "BAREGBEG"],
			['id_kota' => 7, 'nama_kecamatan' => "CIKONENG"],
			['id_kota' => 7, 'nama_kecamatan' => "SINDANGKASIH"],
			['id_kota' => 7, 'nama_kecamatan' => "CIHAURBEUTI"],
			['id_kota' => 7, 'nama_kecamatan' => "SADANANYA"],
			['id_kota' => 7, 'nama_kecamatan' => "CIPAKU"],
			['id_kota' => 7, 'nama_kecamatan' => "JATINAGARA"],
			['id_kota' => 7, 'nama_kecamatan' => "PANAWANGAN"],
			['id_kota' => 7, 'nama_kecamatan' => "KAWALI"],
			['id_kota' => 7, 'nama_kecamatan' => "LUMBUNG"],
			['id_kota' => 7, 'nama_kecamatan' => "PANJALU"],
			['id_kota' => 7, 'nama_kecamatan' => "SUKAMANTRI"],
			['id_kota' => 7, 'nama_kecamatan' => "PANUMBANGAN"],
			['id_kota' => 8, 'nama_kecamatan' => "DARMA"],
			['id_kota' => 8, 'nama_kecamatan' => "KADUGEDE"],
			['id_kota' => 8, 'nama_kecamatan' => "NUSAHERANG"],
			['id_kota' => 8, 'nama_kecamatan' => "CINIRU"],
			['id_kota' => 8, 'nama_kecamatan' => "HANTARA"],
			['id_kota' => 8, 'nama_kecamatan' => "SELAJAMBE"],
			['id_kota' => 8, 'nama_kecamatan' => "SUBANG"],
			['id_kota' => 8, 'nama_kecamatan' => "CILEBAK"],
			['id_kota' => 8, 'nama_kecamatan' => "CIWARU"],
			['id_kota' => 8, 'nama_kecamatan' => "KARANGKANCANA"],
			['id_kota' => 8, 'nama_kecamatan' => "CIBINGBIN"],
			['id_kota' => 8, 'nama_kecamatan' => "CIBEUREUM"],
			['id_kota' => 8, 'nama_kecamatan' => "LURAGUNG"],
			['id_kota' => 8, 'nama_kecamatan' => "CIMAHI"],
			['id_kota' => 8, 'nama_kecamatan' => "CIDAHU"],
			['id_kota' => 8, 'nama_kecamatan' => "KALIMANGGIS"],
			['id_kota' => 8, 'nama_kecamatan' => "CIAWIGEBANG"],
			['id_kota' => 8, 'nama_kecamatan' => "CIPICUNG"],
			['id_kota' => 8, 'nama_kecamatan' => "LEBAKWANGI"],
			['id_kota' => 8, 'nama_kecamatan' => "MALEBER"],
			['id_kota' => 8, 'nama_kecamatan' => "GARAWANGI"],
			['id_kota' => 8, 'nama_kecamatan' => "SINDANGAGUNG"],
			['id_kota' => 8, 'nama_kecamatan' => "KUNINGAN"],
			['id_kota' => 8, 'nama_kecamatan' => "CIGUGUR"],
			['id_kota' => 8, 'nama_kecamatan' => "KRAMATMULYA"],
			['id_kota' => 8, 'nama_kecamatan' => "JALAKSANA"],
			['id_kota' => 8, 'nama_kecamatan' => "JAPARA"],
			['id_kota' => 8, 'nama_kecamatan' => "CILIMUS"],
			['id_kota' => 8, 'nama_kecamatan' => "CIGANDAMEKAR"],
			['id_kota' => 8, 'nama_kecamatan' => "MANDIRANCAN"],
			['id_kota' => 8, 'nama_kecamatan' => "PANCALANG"],
			['id_kota' => 8, 'nama_kecamatan' => "PASAWAHAN"],
			['id_kota' => 9, 'nama_kecamatan' => "WALED"],
			['id_kota' => 9, 'nama_kecamatan' => "PASALEMAN"],
			['id_kota' => 9, 'nama_kecamatan' => "CILEDUG"],
			['id_kota' => 9, 'nama_kecamatan' => "PABUARAN"],
			['id_kota' => 9, 'nama_kecamatan' => "LOSARI"],
			['id_kota' => 9, 'nama_kecamatan' => "PABEDILAN"],
			['id_kota' => 9, 'nama_kecamatan' => "BABAKAN"],
			['id_kota' => 9, 'nama_kecamatan' => "GEBANG"],
			['id_kota' => 9, 'nama_kecamatan' => "KARANGSEMBUNG"],
			['id_kota' => 9, 'nama_kecamatan' => "KARANGWARENG"],
			['id_kota' => 9, 'nama_kecamatan' => "LEMAHABANG"],
			['id_kota' => 9, 'nama_kecamatan' => "SUSUKANLEBAK"],
			['id_kota' => 9, 'nama_kecamatan' => "SEDONG"],
			['id_kota' => 9, 'nama_kecamatan' => "ASTANAJAPURA"],
			['id_kota' => 9, 'nama_kecamatan' => "PANGENAN"],
			['id_kota' => 9, 'nama_kecamatan' => "MUNDU"],
			['id_kota' => 9, 'nama_kecamatan' => "BEBER"],
			['id_kota' => 9, 'nama_kecamatan' => "GREGED"],
			['id_kota' => 9, 'nama_kecamatan' => "TALUN"],
			['id_kota' => 9, 'nama_kecamatan' => "SUMBER"],
			['id_kota' => 9, 'nama_kecamatan' => "DUKUPUNTANG"],
			['id_kota' => 9, 'nama_kecamatan' => "PALIMANAN"],
			['id_kota' => 9, 'nama_kecamatan' => "PLUMBON"],
			['id_kota' => 9, 'nama_kecamatan' => "DEPOK"],
			['id_kota' => 9, 'nama_kecamatan' => "WERU"],
			['id_kota' => 9, 'nama_kecamatan' => "PLERED"],
			['id_kota' => 9, 'nama_kecamatan' => "TENGAH TANI"],
			['id_kota' => 9, 'nama_kecamatan' => "KEDAWUNG"],
			['id_kota' => 9, 'nama_kecamatan' => "GUNUNGJATI"],
			['id_kota' => 9, 'nama_kecamatan' => "KAPETAKAN"],
			['id_kota' => 9, 'nama_kecamatan' => "SURANENGGALA"],
			['id_kota' => 9, 'nama_kecamatan' => "KLANGENAN"],
			['id_kota' => 9, 'nama_kecamatan' => "JAMBLANG"],
			['id_kota' => 9, 'nama_kecamatan' => "ARJAWINANGUN"],
			['id_kota' => 9, 'nama_kecamatan' => "PANGURAGAN"],
			['id_kota' => 9, 'nama_kecamatan' => "CIWARINGIN"],
			['id_kota' => 9, 'nama_kecamatan' => "GEMPOL"],
			['id_kota' => 9, 'nama_kecamatan' => "SUSUKAN"],
			['id_kota' => 9, 'nama_kecamatan' => "GEGESIK"],
			['id_kota' => 9, 'nama_kecamatan' => "KALIWEDI"],
			['id_kota' => 10, 'nama_kecamatan' => "LEMAHSUGIH"],
			['id_kota' => 10, 'nama_kecamatan' => "BANTARUJEG"],
			['id_kota' => 10, 'nama_kecamatan' => "MALAUSMA"],
			['id_kota' => 10, 'nama_kecamatan' => "CIKIJING"],
			['id_kota' => 10, 'nama_kecamatan' => "CINGAMBUL"],
			['id_kota' => 10, 'nama_kecamatan' => "TALAGA"],
			['id_kota' => 10, 'nama_kecamatan' => "BANJARAN"],
			['id_kota' => 10, 'nama_kecamatan' => "ARGAPURA"],
			['id_kota' => 10, 'nama_kecamatan' => "MAJA"],
			['id_kota' => 10, 'nama_kecamatan' => "MAJALENGKA"],
			['id_kota' => 10, 'nama_kecamatan' => "CIGASONG"],
			['id_kota' => 10, 'nama_kecamatan' => "SUKAHAJI"],
			['id_kota' => 10, 'nama_kecamatan' => "SINDANG"],
			['id_kota' => 10, 'nama_kecamatan' => "RAJAGALUH"],
			['id_kota' => 10, 'nama_kecamatan' => "SINDANGWANGI"],
			['id_kota' => 10, 'nama_kecamatan' => "LEUWIMUNDING"],
			['id_kota' => 10, 'nama_kecamatan' => "PALASAH"],
			['id_kota' => 10, 'nama_kecamatan' => "JATIWANGI"],
			['id_kota' => 10, 'nama_kecamatan' => "DAWUAN"],
			['id_kota' => 10, 'nama_kecamatan' => "KASOKANDEL"],
			['id_kota' => 10, 'nama_kecamatan' => "PANYINGKIRAN"],
			['id_kota' => 10, 'nama_kecamatan' => "KADIPATEN"],
			['id_kota' => 10, 'nama_kecamatan' => "KERTAJATI"],
			['id_kota' => 10, 'nama_kecamatan' => "JATITUJUH"],
			['id_kota' => 10, 'nama_kecamatan' => "LIGUNG"],
			['id_kota' => 10, 'nama_kecamatan' => "SUMBERJAYA"],
			['id_kota' => 11, 'nama_kecamatan' => "JATINANGOR"],
			['id_kota' => 11, 'nama_kecamatan' => "CIMANGGUNG"],
			['id_kota' => 11, 'nama_kecamatan' => "TANJUNGSARI"],
			['id_kota' => 11, 'nama_kecamatan' => "SUKASARI"],
			['id_kota' => 11, 'nama_kecamatan' => "PAMULIHAN"],
			['id_kota' => 11, 'nama_kecamatan' => "RANCAKALONG"],
			['id_kota' => 11, 'nama_kecamatan' => "SUMEDANG SELATAN"],
			['id_kota' => 11, 'nama_kecamatan' => "SUMEDANG UTARA"],
			['id_kota' => 11, 'nama_kecamatan' => "GANEAS"],
			['id_kota' => 11, 'nama_kecamatan' => "SITURAJA"],
			['id_kota' => 11, 'nama_kecamatan' => "CISITU"],
			['id_kota' => 11, 'nama_kecamatan' => "DARMARAJA"],
			['id_kota' => 11, 'nama_kecamatan' => "CIBUGEL"],
			['id_kota' => 11, 'nama_kecamatan' => "WADO"],
			['id_kota' => 11, 'nama_kecamatan' => "JATINUNGGAL"],
			['id_kota' => 11, 'nama_kecamatan' => "JATIGEDE"],
			['id_kota' => 11, 'nama_kecamatan' => "TOMO"],
			['id_kota' => 11, 'nama_kecamatan' => "UJUNG JAYA"],
			['id_kota' => 11, 'nama_kecamatan' => "CONGGEANG"],
			['id_kota' => 11, 'nama_kecamatan' => "PASEH"],
			['id_kota' => 11, 'nama_kecamatan' => "CIMALAKA"],
			['id_kota' => 11, 'nama_kecamatan' => "CISARUA"],
			['id_kota' => 11, 'nama_kecamatan' => "TANJUNGKERTA"],
			['id_kota' => 11, 'nama_kecamatan' => "TANJUNGMEDAR"],
			['id_kota' => 11, 'nama_kecamatan' => "BUAHDUA"],
			['id_kota' => 11, 'nama_kecamatan' => "SURIAN"],
			['id_kota' => 12, 'nama_kecamatan' => "HAURGEULIS"],
			['id_kota' => 12, 'nama_kecamatan' => "GANTAR"],
			['id_kota' => 12, 'nama_kecamatan' => "KROYA"],
			['id_kota' => 12, 'nama_kecamatan' => "GABUSWETAN"],
			['id_kota' => 12, 'nama_kecamatan' => "CIKEDUNG"],
			['id_kota' => 12, 'nama_kecamatan' => "TERISI"],
			['id_kota' => 12, 'nama_kecamatan' => "LELEA"],
			['id_kota' => 12, 'nama_kecamatan' => "BANGODUA"],
			['id_kota' => 12, 'nama_kecamatan' => "TUKDANA"],
			['id_kota' => 12, 'nama_kecamatan' => "WIDASARI"],
			['id_kota' => 12, 'nama_kecamatan' => "KERTASEMAYA"],
			['id_kota' => 12, 'nama_kecamatan' => "SUKAGUMIWANG"],
			['id_kota' => 12, 'nama_kecamatan' => "KRANGKENG"],
			['id_kota' => 12, 'nama_kecamatan' => "KARANGAMPEL"],
			['id_kota' => 12, 'nama_kecamatan' => "KEDOKAN BUNDER"],
			['id_kota' => 12, 'nama_kecamatan' => "JUNTINYUAT"],
			['id_kota' => 12, 'nama_kecamatan' => "SLIYEG"],
			['id_kota' => 12, 'nama_kecamatan' => "JATIBARANG"],
			['id_kota' => 12, 'nama_kecamatan' => "BALONGAN"],
			['id_kota' => 12, 'nama_kecamatan' => "INDRAMAYU"],
			['id_kota' => 12, 'nama_kecamatan' => "SINDANG"],
			['id_kota' => 12, 'nama_kecamatan' => "CANTIGI"],
			['id_kota' => 12, 'nama_kecamatan' => "PASEKAN"],
			['id_kota' => 12, 'nama_kecamatan' => "LOHBENER"],
			['id_kota' => 12, 'nama_kecamatan' => "ARAHAN"],
			['id_kota' => 12, 'nama_kecamatan' => "LOSARANG"],
			['id_kota' => 12, 'nama_kecamatan' => "KANDANGHAUR"],
			['id_kota' => 12, 'nama_kecamatan' => "BONGAS"],
			['id_kota' => 12, 'nama_kecamatan' => "ANJATAN"],
			['id_kota' => 12, 'nama_kecamatan' => "SUKRA"],
			['id_kota' => 12, 'nama_kecamatan' => "PATROL"],
			['id_kota' => 13, 'nama_kecamatan' => "SAGALAHERANG"],
			['id_kota' => 13, 'nama_kecamatan' => "SERANGPANJANG"],
			['id_kota' => 13, 'nama_kecamatan' => "JALANCAGAK"],
			['id_kota' => 13, 'nama_kecamatan' => "CIATER"],
			['id_kota' => 13, 'nama_kecamatan' => "CISALAK"],
			['id_kota' => 13, 'nama_kecamatan' => "KASOMALANG"],
			['id_kota' => 13, 'nama_kecamatan' => "TANJUNGSIANG"],
			['id_kota' => 13, 'nama_kecamatan' => "CIJAMBE"],
			['id_kota' => 13, 'nama_kecamatan' => "CIBOGO"],
			['id_kota' => 13, 'nama_kecamatan' => "SUBANG"],
			['id_kota' => 13, 'nama_kecamatan' => "KALIJATI"],
			['id_kota' => 13, 'nama_kecamatan' => "DAWUAN"],
			['id_kota' => 13, 'nama_kecamatan' => "CIPEUNDEUY"],
			['id_kota' => 13, 'nama_kecamatan' => "PABUARAN"],
			['id_kota' => 13, 'nama_kecamatan' => "PATOKBEUSI"],
			['id_kota' => 13, 'nama_kecamatan' => "PURWADADI"],
			['id_kota' => 13, 'nama_kecamatan' => "CIKAUM"],
			['id_kota' => 13, 'nama_kecamatan' => "PAGADEN"],
			['id_kota' => 13, 'nama_kecamatan' => "PAGADEN BARAT"],
			['id_kota' => 13, 'nama_kecamatan' => "CIPUNAGARA"],
			['id_kota' => 13, 'nama_kecamatan' => "COMPRENG"],
			['id_kota' => 13, 'nama_kecamatan' => "BINONG"],
			['id_kota' => 13, 'nama_kecamatan' => "TAMBAKDAHAN"],
			['id_kota' => 13, 'nama_kecamatan' => "CIASEM"],
			['id_kota' => 13, 'nama_kecamatan' => "PAMANUKAN"],
			['id_kota' => 13, 'nama_kecamatan' => "SUKASARI"],
			['id_kota' => 13, 'nama_kecamatan' => "PUSAKANAGARA"],
			['id_kota' => 13, 'nama_kecamatan' => "PUSAKAJAYA"],
			['id_kota' => 13, 'nama_kecamatan' => "LEGONKULON"],
			['id_kota' => 13, 'nama_kecamatan' => "BLANAKAN"],
			['id_kota' => 14, 'nama_kecamatan' => "JATILUHUR"],
			['id_kota' => 14, 'nama_kecamatan' => "SUKASARI"],
			['id_kota' => 14, 'nama_kecamatan' => "MANIIS"],
			['id_kota' => 14, 'nama_kecamatan' => "TEGAL WARU"],
			['id_kota' => 14, 'nama_kecamatan' => "PLERED"],
			['id_kota' => 14, 'nama_kecamatan' => "SUKATANI"],
			['id_kota' => 14, 'nama_kecamatan' => "DARANGDAN"],
			['id_kota' => 14, 'nama_kecamatan' => "BOJONG"],
			['id_kota' => 14, 'nama_kecamatan' => "WANAYASA"],
			['id_kota' => 14, 'nama_kecamatan' => "KIARAPEDES"],
			['id_kota' => 14, 'nama_kecamatan' => "PASAWAHAN"],
			['id_kota' => 14, 'nama_kecamatan' => "PONDOK SALAM"],
			['id_kota' => 14, 'nama_kecamatan' => "PURWAKARTA"],
			['id_kota' => 14, 'nama_kecamatan' => "BABAKANCIKAO"],
			['id_kota' => 14, 'nama_kecamatan' => "CAMPAKA"],
			['id_kota' => 14, 'nama_kecamatan' => "CIBATU"],
			['id_kota' => 14, 'nama_kecamatan' => "BUNGURSARI"],
			['id_kota' => 15, 'nama_kecamatan' => "PANGKALAN"],
			['id_kota' => 15, 'nama_kecamatan' => "TEGALWARU"],
			['id_kota' => 15, 'nama_kecamatan' => "CIAMPEL"],
			['id_kota' => 15, 'nama_kecamatan' => "TELUKJAMBE TIMUR"],
			['id_kota' => 15, 'nama_kecamatan' => "TELUKJAMBE BARAT"],
			['id_kota' => 15, 'nama_kecamatan' => "KLARI"],
			['id_kota' => 15, 'nama_kecamatan' => "CIKAMPEK"],
			['id_kota' => 15, 'nama_kecamatan' => "PURWASARI"],
			['id_kota' => 15, 'nama_kecamatan' => "TIRTAMULYA"],
			['id_kota' => 15, 'nama_kecamatan' => "JATISARI"],
			['id_kota' => 15, 'nama_kecamatan' => "BANYUSARI"],
			['id_kota' => 15, 'nama_kecamatan' => "KOTABARU"],
			['id_kota' => 15, 'nama_kecamatan' => "CILAMAYA WETAN"],
			['id_kota' => 15, 'nama_kecamatan' => "CILAMAYA KULON"],
			['id_kota' => 15, 'nama_kecamatan' => "LEMAHABANG"],
			['id_kota' => 15, 'nama_kecamatan' => "TALAGASARI"],
			['id_kota' => 15, 'nama_kecamatan' => "MAJALAYA"],
			['id_kota' => 15, 'nama_kecamatan' => "KARAWANG TIMUR"],
			['id_kota' => 15, 'nama_kecamatan' => "KARAWANG BARAT"],
			['id_kota' => 15, 'nama_kecamatan' => "RAWAMERTA"],
			['id_kota' => 15, 'nama_kecamatan' => "TEMPURAN"],
			['id_kota' => 15, 'nama_kecamatan' => "KUTAWALUYA"],
			['id_kota' => 15, 'nama_kecamatan' => "RENGASDENGKLOK"],
			['id_kota' => 15, 'nama_kecamatan' => "JAYAKERTA"],
			['id_kota' => 15, 'nama_kecamatan' => "PEDES"],
			['id_kota' => 15, 'nama_kecamatan' => "CILEBAR"],
			['id_kota' => 15, 'nama_kecamatan' => "CIBUAYA"],
			['id_kota' => 15, 'nama_kecamatan' => "TIRTAJAYA"],
			['id_kota' => 15, 'nama_kecamatan' => "BATUJAYA"],
			['id_kota' => 15, 'nama_kecamatan' => "PAKISJAYA"],
			['id_kota' => 16, 'nama_kecamatan' => "SETU"],
			['id_kota' => 16, 'nama_kecamatan' => "SERANG BARU"],
			['id_kota' => 16, 'nama_kecamatan' => "CIKARANG PUSAT"],
			['id_kota' => 16, 'nama_kecamatan' => "CIKARANG SELATAN"],
			['id_kota' => 16, 'nama_kecamatan' => "CIBARUSAH"],
			['id_kota' => 16, 'nama_kecamatan' => "BOJONGMANGU"],
			['id_kota' => 16, 'nama_kecamatan' => "CIKARANG TIMUR"],
			['id_kota' => 16, 'nama_kecamatan' => "KEDUNGWARINGIN"],
			['id_kota' => 16, 'nama_kecamatan' => "CIKARANG UTARA"],
			['id_kota' => 16, 'nama_kecamatan' => "KARANGBAHAGIA"],
			['id_kota' => 16, 'nama_kecamatan' => "CIBITUNG"],
			['id_kota' => 16, 'nama_kecamatan' => "CIKARANG BARAT"],
			['id_kota' => 16, 'nama_kecamatan' => "TAMBUN SELATAN"],
			['id_kota' => 16, 'nama_kecamatan' => "TAMBUN UTARA"],
			['id_kota' => 16, 'nama_kecamatan' => "BABELAN"],
			['id_kota' => 16, 'nama_kecamatan' => "TARUMAJAYA"],
			['id_kota' => 16, 'nama_kecamatan' => "TAMBELANG"],
			['id_kota' => 16, 'nama_kecamatan' => "SUKAWANGI"],
			['id_kota' => 16, 'nama_kecamatan' => "SUKATANI"],
			['id_kota' => 16, 'nama_kecamatan' => "SUKAKARYA"],
			['id_kota' => 16, 'nama_kecamatan' => "PEBAYURAN"],
			['id_kota' => 16, 'nama_kecamatan' => "CABANGBUNGIN"],
			['id_kota' => 16, 'nama_kecamatan' => "MUARA GEMBONG"],
			['id_kota' => 17, 'nama_kecamatan' => "RONGGA"],
			['id_kota' => 17, 'nama_kecamatan' => "GUNUNGHALU"],
			['id_kota' => 17, 'nama_kecamatan' => "SINDANGKERTA"],
			['id_kota' => 17, 'nama_kecamatan' => "CILILIN"],
			['id_kota' => 17, 'nama_kecamatan' => "CIHAMPELAS"],
			['id_kota' => 17, 'nama_kecamatan' => "CIPONGKOR"],
			['id_kota' => 17, 'nama_kecamatan' => "BATUJAJAR"],
			['id_kota' => 17, 'nama_kecamatan' => "SAGULING"],
			['id_kota' => 17, 'nama_kecamatan' => "CIPATAT"],
			['id_kota' => 17, 'nama_kecamatan' => "PADALARANG"],
			['id_kota' => 17, 'nama_kecamatan' => "NGAMPRAH"],
			['id_kota' => 17, 'nama_kecamatan' => "PARONGPONG"],
			['id_kota' => 17, 'nama_kecamatan' => "LEMBANG"],
			['id_kota' => 17, 'nama_kecamatan' => "CISARUA"],
			['id_kota' => 17, 'nama_kecamatan' => "CIKALONG WETAN"],
			['id_kota' => 17, 'nama_kecamatan' => "CIPEUNDEUY"],
			['id_kota' => 18, 'nama_kecamatan' => "CIMERAK"],
			['id_kota' => 18, 'nama_kecamatan' => "CIJULANG"],
			['id_kota' => 18, 'nama_kecamatan' => "CIGUGUR"],
			['id_kota' => 18, 'nama_kecamatan' => "LANGKAPLANCAR"],
			['id_kota' => 18, 'nama_kecamatan' => "PARIGI"],
			['id_kota' => 18, 'nama_kecamatan' => "SIDAMULIH"],
			['id_kota' => 18, 'nama_kecamatan' => "PANGANDARAN"],
			['id_kota' => 18, 'nama_kecamatan' => "KALIPUCANG"],
			['id_kota' => 18, 'nama_kecamatan' => "PADAHERANG"],
			['id_kota' => 18, 'nama_kecamatan' => "MANGUNJAYA"],
			['id_kota' => 19, 'nama_kecamatan' => "BOGOR SELATAN"],
			['id_kota' => 19, 'nama_kecamatan' => "BOGOR TIMUR"],
			['id_kota' => 19, 'nama_kecamatan' => "BOGOR UTARA"],
			['id_kota' => 19, 'nama_kecamatan' => "BOGOR TENGAH"],
			['id_kota' => 19, 'nama_kecamatan' => "BOGOR BARAT"],
			['id_kota' => 19, 'nama_kecamatan' => "TANAH SEREAL"],
			['id_kota' => 20, 'nama_kecamatan' => "BAROS"],
			['id_kota' => 20, 'nama_kecamatan' => "LEMBURSITU"],
			['id_kota' => 20, 'nama_kecamatan' => "CIBEUREUM"],
			['id_kota' => 20, 'nama_kecamatan' => "CITAMIANG"],
			['id_kota' => 20, 'nama_kecamatan' => "WARUDOYONG"],
			['id_kota' => 20, 'nama_kecamatan' => "GUNUNG PUYUH"],
			['id_kota' => 20, 'nama_kecamatan' => "CIKOLE"],
			['id_kota' => 21, 'nama_kecamatan' => "BANDUNG KULON"],
			['id_kota' => 21, 'nama_kecamatan' => "BABAKAN CIPARAY"],
			['id_kota' => 21, 'nama_kecamatan' => "BOJONGLOA KALER"],
			['id_kota' => 21, 'nama_kecamatan' => "BOJONGLOA KIDUL"],
			['id_kota' => 21, 'nama_kecamatan' => "ASTANAANYAR"],
			['id_kota' => 21, 'nama_kecamatan' => "REGOL"],
			['id_kota' => 21, 'nama_kecamatan' => "LENGKONG"],
			['id_kota' => 21, 'nama_kecamatan' => "BANDUNG KIDUL"],
			['id_kota' => 21, 'nama_kecamatan' => "BUAHBATU"],
			['id_kota' => 21, 'nama_kecamatan' => "RANCASARI"],
			['id_kota' => 21, 'nama_kecamatan' => "GEDEBAGE"],
			['id_kota' => 21, 'nama_kecamatan' => "CIBIRU"],
			['id_kota' => 21, 'nama_kecamatan' => "PANYILEUKAN"],
			['id_kota' => 21, 'nama_kecamatan' => "UJUNG BERUNG"],
			['id_kota' => 21, 'nama_kecamatan' => "CINAMBO"],
			['id_kota' => 21, 'nama_kecamatan' => "ARCAMANIK"],
			['id_kota' => 21, 'nama_kecamatan' => "ANTAPANI"],
			['id_kota' => 21, 'nama_kecamatan' => "MANDALAJATI"],
			['id_kota' => 21, 'nama_kecamatan' => "KIARACONDONG"],
			['id_kota' => 21, 'nama_kecamatan' => "BATUNUNGGAL"],
			['id_kota' => 21, 'nama_kecamatan' => "SUMUR BANDUNG"],
			['id_kota' => 21, 'nama_kecamatan' => "ANDIR"],
			['id_kota' => 21, 'nama_kecamatan' => "CICENDO"],
			['id_kota' => 21, 'nama_kecamatan' => "BANDUNG WETAN"],
			['id_kota' => 21, 'nama_kecamatan' => "CIBEUNYING KIDUL"],
			['id_kota' => 21, 'nama_kecamatan' => "CIBEUNYING KALER"],
			['id_kota' => 21, 'nama_kecamatan' => "COBLONG"],
			['id_kota' => 21, 'nama_kecamatan' => "SUKAJADI"],
			['id_kota' => 21, 'nama_kecamatan' => "SUKASARI"],
			['id_kota' => 21, 'nama_kecamatan' => "CIDADAP"],
			['id_kota' => 24, 'nama_kecamatan' => "HARJAMUKTI"],
			['id_kota' => 24, 'nama_kecamatan' => "LEMAHWUNGKUK"],
			['id_kota' => 24, 'nama_kecamatan' => "PEKALIPAN"],
			['id_kota' => 24, 'nama_kecamatan' => "KESAMBI"],
			['id_kota' => 24, 'nama_kecamatan' => "KEJAKSAN"],
			['id_kota' => 25, 'nama_kecamatan' => "PONDOKGEDE"],
			['id_kota' => 25, 'nama_kecamatan' => "JATISAMPURNA"],
			['id_kota' => 25, 'nama_kecamatan' => "PONDOKMELATI"],
			['id_kota' => 25, 'nama_kecamatan' => "JATIASIH"],
			['id_kota' => 25, 'nama_kecamatan' => "BANTARGEBANG"],
			['id_kota' => 25, 'nama_kecamatan' => "MUSTIKAJAYA"],
			['id_kota' => 25, 'nama_kecamatan' => "BEKASI TIMUR"],
			['id_kota' => 25, 'nama_kecamatan' => "RAWALUMBU"],
			['id_kota' => 25, 'nama_kecamatan' => "BEKASI SELATAN"],
			['id_kota' => 25, 'nama_kecamatan' => "BEKASI BARAT"],
			['id_kota' => 25, 'nama_kecamatan' => "MEDAN SATRIA"],
			['id_kota' => 25, 'nama_kecamatan' => "BEKASI UTARA"],
			['id_kota' => 26, 'nama_kecamatan' => "SAWANGAN"],
			['id_kota' => 26, 'nama_kecamatan' => "BOJONGSARI"],
			['id_kota' => 26, 'nama_kecamatan' => "PANCORAN MAS"],
			['id_kota' => 26, 'nama_kecamatan' => "CIPAYUNG"],
			['id_kota' => 26, 'nama_kecamatan' => "SUKMA JAYA"],
			['id_kota' => 26, 'nama_kecamatan' => "CILODONG"],
			['id_kota' => 26, 'nama_kecamatan' => "CIMANGGIS"],
			['id_kota' => 26, 'nama_kecamatan' => "TAPOS"],
			['id_kota' => 26, 'nama_kecamatan' => "BEJI"],
			['id_kota' => 26, 'nama_kecamatan' => "LIMO"],
			['id_kota' => 26, 'nama_kecamatan' => "CINERE"],
			['id_kota' => 27, 'nama_kecamatan' => "CIMAHI SELATAN"],
			['id_kota' => 27, 'nama_kecamatan' => "CIMAHI TENGAH"],
			['id_kota' => 27, 'nama_kecamatan' => "CIMAHI UTARA"],
			['id_kota' => 28, 'nama_kecamatan' => "KAWALU"],
			['id_kota' => 28, 'nama_kecamatan' => "TAMANSARI"],
			['id_kota' => 28, 'nama_kecamatan' => "CIBEUREUM"],
			['id_kota' => 28, 'nama_kecamatan' => "PURBARATU"],
			['id_kota' => 28, 'nama_kecamatan' => "TAWANG"],
			['id_kota' => 28, 'nama_kecamatan' => "CIHIDEUNG"],
			['id_kota' => 28, 'nama_kecamatan' => "MANGKUBUMI"],
			['id_kota' => 28, 'nama_kecamatan' => "INDIHIANG"],
			['id_kota' => 28, 'nama_kecamatan' => "BUNGURSARI"],
			['id_kota' => 28, 'nama_kecamatan' => "CIPEDES"],
			['id_kota' => 29, 'nama_kecamatan' => "BANJAR"],
			['id_kota' => 29, 'nama_kecamatan' => "PURWAHARJA"],
			['id_kota' => 29, 'nama_kecamatan' => "PATARUMAN"],
			['id_kota' => 29, 'nama_kecamatan' => "LANGENSARI"],

        ];
        DB::table('kecamatans')->insert($kecamatan1);
    }
}
