<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kotas = [
        	['kode_kota' => 1101, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN SIMEULUE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1102, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH SINGKIL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1103, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1104, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH TENGGARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1105, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1106, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1107, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1108, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH BESAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1109, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN PIDIE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1110, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN BIREUEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1111, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1112, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH BARAT DAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1113, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN GAYO LUES", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1114, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH TAMIANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1115, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN NAGAN RAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1116, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN ACEH JAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1117, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN BENER MERIAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1118, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN PIDIE JAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1171, 'id_provinsi' => 11, 'nama_kota' => "KOTA BANDA ACEH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1172, 'id_provinsi' => 11, 'nama_kota' => "KOTA SABANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1173, 'id_provinsi' => 11, 'nama_kota' => "KOTA LANGSA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1174, 'id_provinsi' => 11, 'nama_kota' => "KOTA LHOKSEUMAWE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1175, 'id_provinsi' => 11, 'nama_kota' => "KOTA SUBULUSSALAM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1201, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN NIAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1202, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN MANDAILING NATAL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1203, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN TAPANULI SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1204, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN TAPANULI TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1205, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN TAPANULI UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1206, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN TOBA SAMOSIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1207, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN LABUHAN BATU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1208, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN ASAHAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1209, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SIMALUNGUN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1210, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN DAIRI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1211, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN KARO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1212, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN DELI SERDANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1213, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN LANGKAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1214, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN NIAS SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1215, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN HUMBANG HASUNDUTAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1216, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN PAKPAK BHARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1217, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SAMOSIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1218, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SERDANG BEDAGAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1219, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN BATU BARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1220, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN PADANG LAWAS UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1221, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN PADANG LAWAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1222, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN LABUHAN BATU SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1223, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN LABUHAN BATU UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1224, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN NIAS UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1225, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN NIAS BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1271, 'id_provinsi' => 12, 'nama_kota' => "KOTA SIBOLGA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1272, 'id_provinsi' => 12, 'nama_kota' => "KOTA TANJUNG BALAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1273, 'id_provinsi' => 12, 'nama_kota' => "KOTA PEMATANG SIANTAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1274, 'id_provinsi' => 12, 'nama_kota' => "KOTA TEBING TINGGI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1275, 'id_provinsi' => 12, 'nama_kota' => "KOTA MEDAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1276, 'id_provinsi' => 12, 'nama_kota' => "KOTA BINJAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1277, 'id_provinsi' => 12, 'nama_kota' => "KOTA PADANGSIDIMPUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1278, 'id_provinsi' => 12, 'nama_kota' => "KOTA GUNUNGSITOLI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1301, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KEPULAUAN MENTAWAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1302, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PESISIR SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1303, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SOLOK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1304, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SIJUNJUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1305, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN TANAH DATAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1306, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PADANG PARIAMAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1307, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN AGAM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1308, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN LIMA PULUH KOTA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1309, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PASAMAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1310, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SOLOK SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1311, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN DHARMASRAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1312, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PASAMAN BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1371, 'id_provinsi' => 13, 'nama_kota' => "KOTA PADANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1372, 'id_provinsi' => 13, 'nama_kota' => "KOTA SOLOK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1373, 'id_provinsi' => 13, 'nama_kota' => "KOTA SAWAH LUNTO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1374, 'id_provinsi' => 13, 'nama_kota' => "KOTA PADANG PANJANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1375, 'id_provinsi' => 13, 'nama_kota' => "KOTA BUKITTINGGI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1376, 'id_provinsi' => 13, 'nama_kota' => "KOTA PAYAKUMBUH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1377, 'id_provinsi' => 13, 'nama_kota' => "KOTA PARIAMAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1401, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN KUANTAN SINGINGI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1402, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN INDRAGIRI HULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1403, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN INDRAGIRI HILIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1404, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN PELALAWAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1405, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN SIAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1406, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN KAMPAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1407, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN ROKAN HULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1408, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN BENGKALIS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1409, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN ROKAN HILIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1410, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN KEPULAUAN MERANTI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1471, 'id_provinsi' => 14, 'nama_kota' => "KOTA PEKANBARU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1473, 'id_provinsi' => 14, 'nama_kota' => "KOTA DUMAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1501, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN KERINCI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1502, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MERANGIN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1503, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN SAROLANGUN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1504, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BATANG HARI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1505, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MUARO JAMBI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1506, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TANJUNG JABUNG TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1507, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TANJUNG JABUNG BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1508, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TEBO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1509, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BUNGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1571, 'id_provinsi' => 15, 'nama_kota' => "KOTA JAMBI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1572, 'id_provinsi' => 15, 'nama_kota' => "KOTA SUNGAI PENUH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1601, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1602, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN OGAN KOMERING ILIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1603, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN MUARA ENIM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1604, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN LAHAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1605, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN MUSI RAWAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1606, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN MUSI BANYUASIN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1607, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN BANYU ASIN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1608, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1609, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1610, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN OGAN ILIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1611, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN EMPAT LAWANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1612, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN PENUKAL ABAB LEMATANG ILIR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1613, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN MUSI RAWAS UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1671, 'id_provinsi' => 16, 'nama_kota' => "KOTA PALEMBANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1672, 'id_provinsi' => 16, 'nama_kota' => "KOTA PRABUMULIH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1673, 'id_provinsi' => 16, 'nama_kota' => "KOTA PAGAR ALAM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1674, 'id_provinsi' => 16, 'nama_kota' => "KOTA LUBUKLINGGAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1701, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BENGKULU SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1702, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN REJANG LEBONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1703, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BENGKULU UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1704, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN KAUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1705, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN SELUMA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1706, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN MUKOMUKO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1707, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN LEBONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1708, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN KEPAHIANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1709, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BENGKULU TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1771, 'id_provinsi' => 17, 'nama_kota' => "KOTA BENGKULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1801, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LAMPUNG BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1802, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN TANGGAMUS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1803, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LAMPUNG SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1804, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LAMPUNG TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1805, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LAMPUNG TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1806, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LAMPUNG UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1807, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN WAY KANAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1808, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN TULANGBAWANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1809, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN PESAWARAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1810, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN PRINGSEWU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1811, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN MESUJI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1812, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN TULANG BAWANG BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1813, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN PESISIR BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1871, 'id_provinsi' => 18, 'nama_kota' => "KOTA BANDAR LAMPUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1872, 'id_provinsi' => 18, 'nama_kota' => "KOTA METRO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1901, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BANGKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1902, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BELITUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1903, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BANGKA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1904, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BANGKA TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1905, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BANGKA SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1906, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BELITUNG TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 1971, 'id_provinsi' => 19, 'nama_kota' => "KOTA PANGKAL PINANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2101, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KARIMUN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2102, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN BINTAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2103, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN NATUNA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2104, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN LINGGA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2105, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KEPULAUAN ANAMBAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2171, 'id_provinsi' => 21, 'nama_kota' => "KOTA BATAM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 2172, 'id_provinsi' => 21, 'nama_kota' => "KOTA TANJUNG PINANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3101, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN KEPULAUAN SERIBU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3171, 'id_provinsi' => 31, 'nama_kota' => "KOTA JAKARTA SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3172, 'id_provinsi' => 31, 'nama_kota' => "KOTA JAKARTA TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3173, 'id_provinsi' => 31, 'nama_kota' => "KOTA JAKARTA PUSAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3174, 'id_provinsi' => 31, 'nama_kota' => "KOTA JAKARTA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3175, 'id_provinsi' => 31, 'nama_kota' => "KOTA JAKARTA UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3201, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN BOGOR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3202, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN SUKABUMI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3203, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN CIANJUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3204, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN BANDUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3205, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN GARUT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3206, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN TASIKMALAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3207, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN CIAMIS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3208, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN KUNINGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3209, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN CIREBON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3210, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN MAJALENGKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3211, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN SUMEDANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3212, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN INDRAMAYU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3213, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN SUBANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3214, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN PURWAKARTA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3215, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN KARAWANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3216, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN BEKASI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3217, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN BANDUNG BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3218, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN PANGANDARAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3271, 'id_provinsi' => 32, 'nama_kota' => "KOTA BOGOR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3272, 'id_provinsi' => 32, 'nama_kota' => "KOTA SUKABUMI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3273, 'id_provinsi' => 32, 'nama_kota' => "KOTA BANDUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3274, 'id_provinsi' => 32, 'nama_kota' => "KOTA CIREBON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3275, 'id_provinsi' => 32, 'nama_kota' => "KOTA BEKASI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3276, 'id_provinsi' => 32, 'nama_kota' => "KOTA DEPOK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3277, 'id_provinsi' => 32, 'nama_kota' => "KOTA CIMAHI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3278, 'id_provinsi' => 32, 'nama_kota' => "KOTA TASIKMALAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3279, 'id_provinsi' => 32, 'nama_kota' => "KOTA BANJAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3301, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN CILACAP", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3302, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BANYUMAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3303, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PURBALINGGA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3304, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BANJARNEGARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3305, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KEBUMEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3306, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PURWOREJO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3307, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN WONOSOBO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3308, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN MAGELANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3309, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BOYOLALI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3310, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KLATEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3311, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN SUKOHARJO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3312, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN WONOGIRI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3313, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KARANGANYAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3314, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN SRAGEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3315, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN GROBOGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3316, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BLORA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3317, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN REMBANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3318, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PATI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3319, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KUDUS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3320, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN JEPARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3321, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN DEMAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3322, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN SEMARANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3323, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN TEMANGGUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3324, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KENDAL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3325, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BATANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3326, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PEKALONGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3327, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PEMALANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3328, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN TEGAL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3329, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN BREBES", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3371, 'id_provinsi' => 33, 'nama_kota' => "KOTA MAGELANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3372, 'id_provinsi' => 33, 'nama_kota' => "KOTA SURAKARTA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3373, 'id_provinsi' => 33, 'nama_kota' => "KOTA SALATIGA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3374, 'id_provinsi' => 33, 'nama_kota' => "KOTA SEMARANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3375, 'id_provinsi' => 33, 'nama_kota' => "KOTA PEKALONGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3376, 'id_provinsi' => 33, 'nama_kota' => "KOTA TEGAL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3401, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN KULON PROGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3402, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN BANTUL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3403, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN GUNUNG KIDUL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3404, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN SLEMAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3471, 'id_provinsi' => 34, 'nama_kota' => "KOTA YOGYAKARTA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3501, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN PACITAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3502, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN PONOROGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3503, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN TRENGGALEK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3504, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN TULUNGAGUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3505, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN BLITAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3506, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN KEDIRI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3507, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN MALANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3508, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN LUMAJANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3509, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN JEMBER", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3510, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN BANYUWANGI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3511, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN BONDOWOSO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3512, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN SITUBONDO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3513, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN PROBOLINGGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3514, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN PASURUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3515, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN SIDOARJO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3516, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN MOJOKERTO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3517, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN JOMBANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3518, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN NGANJUK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3519, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN MADIUN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3520, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN MAGETAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3521, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN NGAWI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3522, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN BOJONEGORO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3523, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN TUBAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3524, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN LAMONGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3525, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN GRESIK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3526, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN BANGKALAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3527, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN SAMPANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3528, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN PAMEKASAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3529, 'id_provinsi' => 35, 'nama_kota' => "KABUPATEN SUMENEP", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3571, 'id_provinsi' => 35, 'nama_kota' => "KOTA KEDIRI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3572, 'id_provinsi' => 35, 'nama_kota' => "KOTA BLITAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3573, 'id_provinsi' => 35, 'nama_kota' => "KOTA MALANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3574, 'id_provinsi' => 35, 'nama_kota' => "KOTA PROBOLINGGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3575, 'id_provinsi' => 35, 'nama_kota' => "KOTA PASURUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3576, 'id_provinsi' => 35, 'nama_kota' => "KOTA MOJOKERTO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3577, 'id_provinsi' => 35, 'nama_kota' => "KOTA MADIUN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3578, 'id_provinsi' => 35, 'nama_kota' => "KOTA SURABAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3579, 'id_provinsi' => 35, 'nama_kota' => "KOTA BATU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3601, 'id_provinsi' => 36, 'nama_kota' => "KABUPATEN PANDEGLANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3602, 'id_provinsi' => 36, 'nama_kota' => "KABUPATEN LEBAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3603, 'id_provinsi' => 36, 'nama_kota' => "KABUPATEN TANGERANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3604, 'id_provinsi' => 36, 'nama_kota' => "KABUPATEN SERANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3671, 'id_provinsi' => 36, 'nama_kota' => "KOTA TANGERANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3672, 'id_provinsi' => 36, 'nama_kota' => "KOTA CILEGON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3673, 'id_provinsi' => 36, 'nama_kota' => "KOTA SERANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 3674, 'id_provinsi' => 36, 'nama_kota' => "KOTA TANGERANG SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5101, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN JEMBRANA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5102, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN TABANAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5103, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN BADUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5104, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN GIANYAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5105, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN KLUNGKUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5106, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN BANGLI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5107, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN KARANG ASEM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5108, 'id_provinsi' => 51, 'nama_kota' => "KABUPATEN BULELENG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5171, 'id_provinsi' => 51, 'nama_kota' => "KOTA DENPASAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5201, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN LOMBOK BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5202, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN LOMBOK TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5203, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN LOMBOK TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5204, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN SUMBAWA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5205, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN DOMPU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5206, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN BIMA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5207, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN SUMBAWA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5208, 'id_provinsi' => 52, 'nama_kota' => "KABUPATEN LOMBOK UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5271, 'id_provinsi' => 52, 'nama_kota' => "KOTA MATARAM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5272, 'id_provinsi' => 52, 'nama_kota' => "KOTA BIMA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5301, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SUMBA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5302, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SUMBA TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5303, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN KUPANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5304, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN TIMOR TENGAH SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5305, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN TIMOR TENGAH UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5306, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN BELU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5307, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN ALOR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5308, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN LEMBATA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5309, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN FLORES TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5310, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SIKKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5311, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN ENDE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5312, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN NGADA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5313, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN MANGGARAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5314, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN ROTE NDAO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5315, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN MANGGARAI BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5316, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SUMBA TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5317, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SUMBA BARAT DAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5318, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN NAGEKEO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5319, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN MANGGARAI TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5320, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN SABU RAIJUA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5321, 'id_provinsi' => 53, 'nama_kota' => "KABUPATEN MALAKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 5371, 'id_provinsi' => 53, 'nama_kota' => "KOTA KUPANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6101, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN SAMBAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6102, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN BENGKAYANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6103, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN LANDAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6104, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN MEMPAWAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6105, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN SANGGAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6106, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN KETAPANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6107, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN SINTANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6108, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN KAPUAS HULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6109, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN SEKADAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6110, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN MELAWI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6111, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN KAYONG UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6112, 'id_provinsi' => 61, 'nama_kota' => "KABUPATEN KUBU RAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6171, 'id_provinsi' => 61, 'nama_kota' => "KOTA PONTIANAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6172, 'id_provinsi' => 61, 'nama_kota' => "KOTA SINGKAWANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6201, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN KOTAWARINGIN BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6202, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN KOTAWARINGIN TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6203, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN KAPUAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6204, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN BARITO SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6205, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN BARITO UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6206, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN SUKAMARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6207, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN LAMANDAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6208, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN SERUYAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6209, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN KATINGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6210, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN PULANG PISAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6211, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN GUNUNG MAS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6212, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN BARITO TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6213, 'id_provinsi' => 62, 'nama_kota' => "KABUPATEN MURUNG RAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6271, 'id_provinsi' => 62, 'nama_kota' => "KOTA PALANGKA RAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6301, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN TANAH LAUT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6302, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN KOTA BARU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6303, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN BANJAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6304, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN BARITO KUALA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6305, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN TAPIN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6306, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN HULU SUNGAI SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6307, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN HULU SUNGAI TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6308, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN HULU SUNGAI UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6309, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN TABALONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6310, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN TANAH BUMBU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6311, 'id_provinsi' => 63, 'nama_kota' => "KABUPATEN BALANGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6371, 'id_provinsi' => 63, 'nama_kota' => "KOTA BANJARMASIN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6372, 'id_provinsi' => 63, 'nama_kota' => "KOTA BANJAR BARU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6401, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN PASER", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6402, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN KUTAI BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6403, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN KUTAI KARTANEGARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6404, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN KUTAI TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6405, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN BERAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6409, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN PENAJAM PASER UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6411, 'id_provinsi' => 64, 'nama_kota' => "KABUPATEN MAHAKAM HULU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6471, 'id_provinsi' => 64, 'nama_kota' => "KOTA BALIKPAPAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6472, 'id_provinsi' => 64, 'nama_kota' => "KOTA SAMARINDA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6474, 'id_provinsi' => 64, 'nama_kota' => "KOTA BONTANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6501, 'id_provinsi' => 65, 'nama_kota' => "KABUPATEN MALINAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6502, 'id_provinsi' => 65, 'nama_kota' => "KABUPATEN BULUNGAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6503, 'id_provinsi' => 65, 'nama_kota' => "KABUPATEN TANA TIDUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6504, 'id_provinsi' => 65, 'nama_kota' => "KABUPATEN NUNUKAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 6571, 'id_provinsi' => 65, 'nama_kota' => "KOTA TARAKAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7101, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7102, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN MINAHASA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7103, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN KEPULAUAN SANGIHE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7104, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN KEPULAUAN TALAUD", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7105, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN MINAHASA SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7106, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN MINAHASA UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7107, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7108, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN SIAU TAGULANDANG BIARO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7109, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN MINAHASA TENGGARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7110, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7111, 'id_provinsi' => 71, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7171, 'id_provinsi' => 71, 'nama_kota' => "KOTA MANADO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7172, 'id_provinsi' => 71, 'nama_kota' => "KOTA BITUNG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7173, 'id_provinsi' => 71, 'nama_kota' => "KOTA TOMOHON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7174, 'id_provinsi' => 71, 'nama_kota' => "KOTA KOTAMOBAGU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7201, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN BANGGAI KEPULAUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7202, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN BANGGAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7203, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN MOROWALI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7204, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN POSO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7205, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN DONGGALA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7206, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN TOLI-TOLI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7207, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN BUOL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7208, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN PARIGI MOUTONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7209, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN TOJO UNA-UNA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7210, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN SIGI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7211, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN BANGGAI LAUT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7212, 'id_provinsi' => 72, 'nama_kota' => "KABUPATEN MOROWALI UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7271, 'id_provinsi' => 72, 'nama_kota' => "KOTA PALU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7301, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN KEPULAUAN SELAYAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7302, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN BULUKUMBA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7303, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN BANTAENG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7304, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN JENEPONTO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7305, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN TAKALAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7306, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN GOWA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7307, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN SINJAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7308, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN MAROS", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7309, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN PANGKAJENE DAN KEPULAUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7310, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN BARRU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7311, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN BONE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7312, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN SOPPENG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7313, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN WAJO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7314, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN SIDENRENG RAPPANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7315, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN PINRANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7316, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN ENREKANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7317, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN LUWU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7318, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN TANA TORAJA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7322, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN LUWU UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7325, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN LUWU TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7326, 'id_provinsi' => 73, 'nama_kota' => "KABUPATEN TORAJA UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7371, 'id_provinsi' => 73, 'nama_kota' => "KOTA MAKASSAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7372, 'id_provinsi' => 73, 'nama_kota' => "KOTA PAREPARE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7373, 'id_provinsi' => 73, 'nama_kota' => "KOTA PALOPO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7401, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN BUTON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7402, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN MUNA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7403, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KONAWE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7404, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KOLAKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7405, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KONAWE SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7406, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN BOMBANA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7407, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN WAKATOBI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7408, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KOLAKA UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7409, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN BUTON UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7410, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KONAWE UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7411, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KOLAKA TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7412, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN KONAWE KEPULAUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7413, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN MUNA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7414, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN BUTON TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7415, 'id_provinsi' => 74, 'nama_kota' => "KABUPATEN BUTON SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7471, 'id_provinsi' => 74, 'nama_kota' => "KOTA KENDARI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7472, 'id_provinsi' => 74, 'nama_kota' => "KOTA BAUBAU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7501, 'id_provinsi' => 75, 'nama_kota' => "KABUPATEN BOALEMO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7502, 'id_provinsi' => 75, 'nama_kota' => "KABUPATEN GORONTALO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7503, 'id_provinsi' => 75, 'nama_kota' => "KABUPATEN POHUWATO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7504, 'id_provinsi' => 75, 'nama_kota' => "KABUPATEN BONE BOLANGO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7505, 'id_provinsi' => 75, 'nama_kota' => "KABUPATEN GORONTALO UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7571, 'id_provinsi' => 75, 'nama_kota' => "KOTA GORONTALO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7601, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN MAJENE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7602, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN POLEWALI MANDAR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7603, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN MAMASA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7604, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN MAMUJU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7605, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN MAMUJU UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 7606, 'id_provinsi' => 76, 'nama_kota' => "KABUPATEN MAMUJU TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8101, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN MALUKU TENGGARA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8102, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN MALUKU TENGGARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8103, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN MALUKU TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8104, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN BURU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8105, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN KEPULAUAN ARU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8106, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN SERAM BAGIAN BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8107, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN SERAM BAGIAN TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8108, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN MALUKU BARAT DAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8109, 'id_provinsi' => 81, 'nama_kota' => "KABUPATEN BURU SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8171, 'id_provinsi' => 81, 'nama_kota' => "KOTA AMBON", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8172, 'id_provinsi' => 81, 'nama_kota' => "KOTA TUAL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8201, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN HALMAHERA BARAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8202, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN HALMAHERA TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8203, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN KEPULAUAN SULA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8204, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN HALMAHERA SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8205, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN HALMAHERA UTARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8206, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN HALMAHERA TIMUR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8207, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN PULAU MOROTAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8208, 'id_provinsi' => 82, 'nama_kota' => "KABUPATEN PULAU TALIABU", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8271, 'id_provinsi' => 82, 'nama_kota' => "KOTA TERNATE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 8272, 'id_provinsi' => 82, 'nama_kota' => "KOTA TIDORE KEPULAUAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9101, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN FAKFAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9102, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN KAIMANA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9103, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN TELUK WONDAMA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9104, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN TELUK BINTUNI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9105, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN MANOKWARI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9106, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN SORONG SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9107, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN SORONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9108, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN RAJA AMPAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9109, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN TAMBRAUW", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9110, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN MAYBRAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9111, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN MANOKWARI SELATAN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9112, 'id_provinsi' => 91, 'nama_kota' => "KABUPATEN PEGUNUNGAN ARFAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9171, 'id_provinsi' => 91, 'nama_kota' => "KOTA SORONG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9401, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN MERAUKE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9402, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN JAYAWIJAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9403, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN JAYAPURA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9404, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN NABIRE", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9408, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN KEPULAUAN YAPEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9409, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN BIAK NUMFOR", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9410, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN PANIAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9411, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN PUNCAK JAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9412, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN MIMIKA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9413, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN BOVEN DIGOEL", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9414, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN MAPPI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9415, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN ASMAT", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9416, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN YAHUKIMO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9417, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN PEGUNUNGAN BINTANG", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9418, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN TOLIKARA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9419, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN SARMI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9420, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN KEEROM", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9426, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN WAROPEN", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9427, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN SUPIORI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9428, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN MAMBERAMO RAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9429, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN NDUGA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9430, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN LANNY JAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9431, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN MAMBERAMO TENGAH", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9432, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN YALIMO", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9433, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN PUNCAK", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9434, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN DOGIYAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9435, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN INTAN JAYA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9436, 'id_provinsi' => 94, 'nama_kota' => "KABUPATEN DEIYAI", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['kode_kota' => 9471, 'id_provinsi' => 94, 'nama_kota' => "KOTA JAYAPURA", 'created_at' => Carbon::now()->format('Y-m-d H:i:s'), 'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]
        ];
        DB::table('kotas')->insert($kotas);
    }
}
